*** Variables ***
${PROJECT_ROOT}                ${CURDIR}/../../    # Adjust based on file location
${DATA_DIR}                    ${PROJECT_ROOT}/data
${BASE_URL}                     https://serverest.dev
${ENDPOINT_USUARIOS}            /usuarios
${ENDPOINT_LOGIN}               /login
&{HEADERS}                      Content-Type=application/json
${EXPECTED_STATUS_CODE}         
${EXPECTED_MESSAGE}
     
